version: "3"

services:
  # acme_sh:
  #   image: neilpang/acme.sh
  #   command: acme.sh --daemon
  #   volumes:
  #     - ./certs:/acme.sh
  casdoor:
    image: casbin/casdoor-all-in-one
  casdoor_proxy:
    image: nginx
    volumes:
    - ./nginx:/etc/nginx
    - ./certs:/certs
    ports:
    - 8080:80
    - 8443:443
  
  
  video_server:
    build: ./video_server
    env_file:
    - ./video_server/.env
    environment:
    - NODE_EXTRA_CA_CERTS=/ca.cer
    ports:
    - 8081:8080
    volumes:
    - ./certs/tcub.site_ecc/ca.cer:/ca.cer
    
  # video_db:
  #   image: mysql:latest
  #   environments:
  #   - MYSQL_ROOT_PASSWORD=39jeslHEHR
