version: "3"

services:
  # acme_sh:
  #   image: neilpang/acme.sh
  #   command: acme.sh --cron
  #   volumes:
  #     - ./certs:/acme.sh
  casdoor:
    image: casbin/casdoor
    volumes:
    - ./casdoor_conf:/conf
    depends_on:
    - casdoor_db
  casdoor_db:
    image: mysql:latest
    volumes:
    - ./casdoor_db:/var/lib/mysql
    environment:
    - MYSQL_ROOT_PASSWORD=ri9eq4ji4YEW
    - MYSQL_DATABASE=casdoor
  casdoor_proxy:
    image: nginx
    volumes:
    - ./nginx:/etc/nginx
    - ./certs:/certs
    depends_on:
    - casdoor
    ports:
    - 8080:80
    - 8443:443
  
  
  video_server:
    build: ./video_server
    env_file:
    - ./video_server/.env
    environment:
    - NODE_EXTRA_CA_CERTS=/ca.cer
    ports:
    - 8081:8080
    volumes:
    - ./certs/tcub.site_ecc/ca.cer:/ca.cer
    
  # video_db:
  #   image: mysql:latest
  #   environments:
  #   - MYSQL_ROOT_PASSWORD=39jeslHEHR
